force-app/main/default/objects/MyOffer__c/MyOffer__c.object-meta.xml
<CustomObject>
    <label>MyOffer</label>
    <nameField>
        <label>MyOffer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyOffers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyOffer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MyOffers</relationshipLabel>
    <relationshipName>MyOffers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag1__c.field-meta.xml
<CustomField>
    <fullName>Tag1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag1</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers</relationshipLabel>
    <relationshipName>MyOffers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag2__c.field-meta.xml
<CustomField>
    <fullName>Tag2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag2</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag2)</relationshipLabel>
    <relationshipName>MyOffers1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag3__c.field-meta.xml
<CustomField>
    <fullName>Tag3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag3</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag3)</relationshipLabel>
    <relationshipName>MyOffers2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag4__c.field-meta.xml
<CustomField>
    <fullName>Tag4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag4</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag4)</relationshipLabel>
    <relationshipName>MyOffers3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OfferTag__c/OfferTag__c.object-meta.xml
<CustomObject>
    <label>OfferTag</label>
    <nameField>
        <label>OfferTag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OfferTags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GenerateData.cls
public with sharing class GenerateData{
  public void generateAccounts(){

    System.debug('tests');

    List<Account> accounts = new List<Account>();

    List<String> accountNames = new List<String>{ 'Amanda', 'Jon', 'Valentina', 'Francis' };

    for (Integer i = 0; i < accountNames.size(); i++){

      Account account = new Account();
      account.Name = accountNames[i];

      accounts.add(account);
    }
    insert accounts;

    for (Account account : accounts){

      generateMyOffersAndAddOfferTags(account);
    }
  }

  public void generateMyOffersAndAddOfferTags(Account account){

    List<OfferTag__c> offerTags = new List<OfferTag__c>();
    List<MyOffer__c> myOffers = new List<MyOffer__c>();

    for (Integer i = 0; i < 4; i++){
      offerTags = generateOfferTags();
      MyOffer__c myOffer1 = new MyOffer__c(Account__c = account.id, Name = 'Investice ' + i, Tag1__c = offerTags.get(0).Id, Tag2__c = offerTags.get(1).Id, Tag3__c = offerTags.get(2).Id, Tag4__c = offerTags.get(3).Id);

      myOffers.add(myOffer1);
    }
    insert myOffers;
  }

  public List<OfferTag__c> generateOfferTags(){

    List<OfferTag__c> offerTags = new List<OfferTag__c>();

    for (Integer i = 0; i < 4; i++){
      OfferTag__c offerTag1 = new OfferTag__c(Name = 'Tag ' + i);
      offerTags.add(offerTag1);
    }

    insert offerTags;
    return offerTags;
  }
}