force-app/main/default/objects/MyOffer__c/MyOffer__c.object-meta.xml
<CustomObject>
    <label>MyOffer</label>
    <nameField>
        <label>MyOffer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MyOffers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MyOffer__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MyOffers</relationshipLabel>
    <relationshipName>MyOffers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag1__c.field-meta.xml
<CustomField>
    <fullName>Tag1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag1</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers</relationshipLabel>
    <relationshipName>MyOffers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag2__c.field-meta.xml
<CustomField>
    <fullName>Tag2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag2</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag2)</relationshipLabel>
    <relationshipName>MyOffers1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag3__c.field-meta.xml
<CustomField>
    <fullName>Tag3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag3</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag3)</relationshipLabel>
    <relationshipName>MyOffers2</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MyOffer__c/fields/Tag4__c.field-meta.xml
<CustomField>
    <fullName>Tag4__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tag4</label>
    <referenceTo>OfferTag__c</referenceTo>
    <relationshipLabel>MyOffers (Tag4)</relationshipLabel>
    <relationshipName>MyOffers3</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OfferTag__c/OfferTag__c.object-meta.xml
<CustomObject>
    <label>OfferTag</label>
    <nameField>
        <label>OfferTag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OfferTags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FirstTask.cls
public with sharing class FirstTask {
 
    public FirstTask() {
        createAccount();
    }

    private void createAccount(){
        
        List<Account> acct = [SELECT Id,Name FROM Account WHERE NAME = 'Amanda' OR NAME = 'Jon' OR NAME = 'Francis' OR NAME = 'Valentina'];
        delete acct;
        List<Account> accountList = new List<Account>();
        List<String> accountNames = new List<String>{'Amanda','Jon','Valentina','Francis'};

        for (Integer i=0; i < 4;i++) {
                Account account = new Account();   
                createMyOffers(account);
                account.Name = accountNames.get(i);
                accountList.add(account);
        }
        insert accountList;
    }

    public void createMyOffers(Account account){

        List<OfferTag__c> offerTagyList = new List<OfferTag__c>();
        List<MyOffer__c> myOffersList = new List<MyOffer__c>();

            for(Integer i = 0; i < 4; i++){
                
                offerTagyList = createOfferTags();

                MyOffer__c myOffer = new MyOffer__c();
                myOffer.Account__c = account.Id;
                myOffer.Name = 'Bono '+i;
                myOffer.Tag1__c = offerTagyList.get(0).Id;
                myOffer.Tag2__c = offerTagyList.get(1).Id;
                myOffer.Tag3__c = offerTagyList.get(2).Id;
                myOffer.Tag4__c = offerTagyList.get(3).Id; 
                myOffersList.add(myOffer);
            }
        insert myOffersList;
    }
 
    public List<OfferTag__c> createOfferTags(){
        
        List<OfferTag__c> offerTagyList = new List<OfferTag__c>(); 

            for(Integer i = 0; i < 4; i++){

                OfferTag__c offerTag = new OfferTag__c();
                offerTag.Name = 'Tag '+i;
                offerTagyList.add(offerTag);      
            }
        insert offerTagyList;
        return offerTagyList;
    } 
}